on: 
  pull_request:
    types: [closed]
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /
        protocol: ftps
        port: 21
        timeout: 600000