name: 🚀 Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Install LFTP
      run: sudo apt-get update && sudo apt-get install -y lftp
    
    - name: 🚀 Deploy to FTP
      run: |
        lftp -c "
          set ssl:verify-certificate false;
          set ftp:ssl-allow true;
          set ftp:ssl-force false;
          set net:reconnect-interval-base 5;
          set net:max-retries 5;
          set net:timeout 30;
          set ftp:passive-mode true;
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }};
          lcd ${{ github.workspace }};
          cd /;
          mirror -Rev --delete --verbose --exclude-glob .git/ --exclude-glob .github/ --exclude-glob node_modules/ --exclude-glob '*.log';
          quit
        "
